spring:
    application:
        name: raven-api
    datasource:
        url: jdbc:postgresql://localhost:5432/raven
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        redirect-uri: ${GOOGLE_REDIRECT_URI}
                        scope: profile, email

auth:
    key: db817e58a46f1dd542ecb9fea1f6c020e20a391a9c0abba39b593862a7ae4646