spring:
    application:
        name: raven-api
    datasource:
        url: jdbc:postgresql://localhost:5432/raven
        username: raven_admin
        password: qzwxecdsa
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            client:
                registration:
                    google:

                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        scope: profile, email

auth:
    key: db817e58a46f1dd542ecb9fea1f6c020e20a391a9c0abba39b593862a7ae4646